name = "gleam_crypto"
version = "0.4.0"
gleam = ">= 0.30.0"

licences = ["Apache-2.0"]
description = "Gleam bindings to the BEAM cryptography functions"

repository = { type = "github", user = "gleam-experiments", repo = "crypto" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = "~> 0.19"
gleam_bitwise = "~> 1.1"

[dev-dependencies]
gleeunit = "~> 0.5"
